-- Extensions installed by users (from Open VSX or upload). See the notes at the
-- top of 000001 for the per-engine type choices; `id` is generated by the
-- process, JSON columns are always bound, and DATETIME(6) holds UTC.
CREATE TABLE code.extensions (
    id           BINARY(16)   NOT NULL PRIMARY KEY,
    user_id      BINARY(16)   NOT NULL,
    publisher    VARCHAR(100) NOT NULL,
    name         VARCHAR(100) NOT NULL,
    version      VARCHAR(50)  NOT NULL,
    display_name VARCHAR(255),
    description  TEXT,
    install_path TEXT         NOT NULL,
    manifest     JSON         NOT NULL,
    is_enabled   BOOLEAN      NOT NULL DEFAULT TRUE,
    installed_at DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE (user_id, publisher, name)
);

CREATE INDEX idx_code_ext_user ON code.extensions (user_id);
