-- See the notes at the top of 000001 for the per-engine type choices: `id` is
-- generated by the process, the manifest JSON is stored as TEXT and always
-- bound, and timestamps are UTC TEXT.
CREATE TABLE code.extensions (
    id           BLOB    NOT NULL PRIMARY KEY,
    user_id      BLOB    NOT NULL,
    publisher    TEXT    NOT NULL,
    name         TEXT    NOT NULL,
    version      TEXT    NOT NULL,
    display_name TEXT,
    description  TEXT,
    install_path TEXT    NOT NULL,
    manifest     TEXT    NOT NULL,
    is_enabled   INTEGER NOT NULL DEFAULT 1,
    installed_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')),
    UNIQUE (user_id, publisher, name)
);

CREATE INDEX code.idx_code_ext_user ON extensions (user_id);
